name: Wasm 

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  wasm_test:
    name: Execute tests on WASM
    strategy:
      fail-fast: false
      matrix:
        swift_version: ["5.10.0-RELEASE", "6.0-SNAPSHOT-2024-09-18-a"]
        os: [ubuntu-22.04]
        extra_params: [""]
        include:
          - swift_version: "6.0-SNAPSHOT-2024-09-18-a"
            continue-on-error: true
          - swift_version: "5.10.0-RELEASE"
            continue-on-error: false
    runs-on: ${{ matrix.os }}
    env:
      OPENSWIFTUI_WERROR: 1
      OPENGRAPH_ATTRIBUTEGRAPH: 0
      OPENSWIFTUI_COMPATIBILITY_TEST: 0
      OPENSWIFTUI_SWIFT_LOG: 1
      OPENSWIFTUI_SWIFT_CRYPTO: 1
    steps:
      - uses: actions/checkout@v4
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: wasm-${{ matrix.swift_version }}
      - name: build
        run: |
          swift build --triple wasm32-unknown-wasi ${{ matrix.extra_params }}
        continue-on-error: ${{ matrix.continue-on-error }}
      # Blocked by upstream support for WASM. See https://github.com/apple/swift-testing/issues/228
      # - name: test
      #   run: |
      #     swift test --triple wasm32-unknown-wasi ${{ matrix.extra_params }}